os:
    - linux

language: python
python:
    - 3.7
    - 3.8
    - 3.9
    - 3.10
    - 3.11

install:
    - python setup.py install

script:
    - echo 268642 > /tmp/test.txt
    - nhentai --cookie "cf_clearance=xdi9J4Um10.46QzT_S3O13bUgdsGN87yhIBAn7G38HY-1675608138-0-160; csrftoken=zV4qotZJrHKTeEc9uEg5uvXV5qwTcZIHRjF3TgbkvP6OoxZNj8I6RFQeGSSiZT04; sessionid=t2x0ke3u5i1azg2kvepe7w0ej89btc7t"
    - nhentai --useragent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
    - nhentai --search umaru
    - nhentai --id 152503 146134 -t 10 --output=/tmp/ --cbz
    - nhentai -F
    - nhentai --file /tmp/test.txt
    - nhentai --id 152503 146134 --gen-main --output=/tmp/
